version: "3.9"

services:
  app:
    build: ./
    ports:
      - 127.0.0.1:8082:8080
      - 127.0.0.1:8081:8081
    depends_on:
      - migrate
  db:
    image: postgres
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./database/migrate:/migration
    entrypoint:
      [
        "migrate",
        "-path",
        "/migration",
        "-database",
        "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure