version: "3.9"

services:
  app2:
    build: ./
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - migrate2
  db2:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate2:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migration
    entrypoint:
      [
        "migrate",
        "-path",
        "/migration",
        "-database",
        "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}",
      ]
    command: ["up"]
    depends_on:
      db2:
        condition: service_healthy
    restart: on-failure