# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-UserService:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.4

      - name: Install dependencies for UserService
        run: cd UserService && go get -v -t ./...
        
      - name: Install ginkgo for UserService
        run: go install github.com/onsi/ginkgo/ginkgo@latest

      - name: Run tests for UserService
        run: cd UserService && ginkgo ./...

  test-TaskService:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.4

      - name: Install dependencies for TaskService
        run: cd TaskService && go get -v -t ./...
        
      - name: Install ginkgo for UserService
        run: go install github.com/onsi/ginkgo/ginkgo@latest

      - name: Run tests for TaskService
        run: cd TaskService && ginkgo ./...
